# Generated by Django 5.1.6 on 2025-03-29 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_expense_split_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='expenseshare',
            options={'ordering': ['-expense__date', 'user__username']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage')], db_index=True, default='equal', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseshare',
            name='amount_owed',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='expenseshare',
            unique_together={('expense', 'user')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'group'], name='myapp_expen_date_0b03d5_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by', 'group'], name='myapp_expen_paid_by_cace0a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['amount', 'split_type'], name='myapp_expen_amount_758788_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseshare',
            index=models.Index(fields=['user', 'expense'], name='myapp_expen_user_id_10e06a_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseshare',
            index=models.Index(fields=['amount_owed'], name='myapp_expen_amount__4d79cf_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='myapp_group_name_81d429_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['date', 'group'], name='myapp_settl_date_e232e6_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['payer', 'payee'], name='myapp_settl_payer_i_a4c5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['amount'], name='myapp_settl_amount_9f4457_idx'),
        ),
    ]
